---
# This playbook uses the win_get_url module to download a simple HTML file for IIS
- name: Download simple web site 
  hosts: all 

  gather_facts: false
  tasks:
    - name: Download simple web site to 'C:\inetpub\wwwroot\ansible.html'
      win_get_url:
        url: 'https://s3-ap-southeast-1.amazonaws.com/scbdemo/index.html'
        dest: 'C:\inetpub\wwwroot\ansible.html'
